// examples/vue/src/App.vue
<template>
  <div class="game">
    <div class="game-board">
      <Board
        :x-is-next="xIsNext"
        :squares="currentSquares"
        @play="handlePlay"
      />
    </div>
    <div class="game-info">
      <ol>
        <li v-for="(_, idx) in history" :key="`l-${idx}`">
          <button @click="jumpTo(idx)">
            Go to {{ idx > 0 ? `move #${idx}` : 'game start' }}
          </button>
        </li>
      </ol>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue';

import Board from './board.vue';

const history = ref<string[][]>([[...Array(9).fill('')]] as string[][]);
const currentMove = ref(0);

const xIsNext = computed(() => currentMove.value % 2 === 0);
const currentSquares = computed(() => history.value[currentMove.value]);

const jumpTo = (step: number) => {
  currentMove.value = step;
};

const handlePlay = (nextSquares: string[]) => {
  const nextHistory = [
    ...history.value.slice(0, currentMove.value + 1),
    nextSquares
  ];

  history.value = nextHistory;
  currentMove.value = nextHistory.length - 1;
};
</script>

// examples/react/src/App.tsx
import React, { useCallback, useMemo, useState } from 'react';

import Board from './board';

const Game = React.memo(() => {
  const [history, setHistory] = useState<string[][]>([Array(9).fill('')]);
  const [currentMove, setCurrentMove] = useState(0);
  const xIsNext = currentMove % 2 === 0;
  const currentSquares = history[currentMove];

  const handlePlay = useCallback(
    (nextSquares: string[]) => {
      const nextHistory = [...history.slice(0, currentMove + 1), nextSquares];
      setHistory(nextHistory);
      setCurrentMove(nextHistory.length - 1);
    },
    [currentMove, history]
  );

  const historyMoves = useMemo(
    () =>
      history.map((_, index) => {
        let description: string;

        if (index > 0) {
          description = 'Go to move #' + index;
        } else {
          description = 'Go to game start';
        }

        return (
          <li key={index}>
            <button onClick={() => setCurrentMove(index)}>{description}</button>
          </li>
        );
      }),
    [history]
  );

  return (
    <div className="game">
      <div className="game-board">
        <Board xIsNext={xIsNext} squares={currentSquares} onPlay={handlePlay} />
      </div>
      <div className="game-info">
        <ol>{historyMoves}</ol>
      </div>
    </div>
  );
});

export default Game;
